import time
import webbrowser
print ("In 90 Minuten ist Pause")
time.sleep(5400)
print("Pause!")
time.sleep(2)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(199)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(251)
print("7,5 Minütige Pause ist um")
time.sleep(5400)
print("Pause für dich!")
time.sleep(2)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(199)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(251)
print(" 7,5 Minütige Pause ist um")
time.sleep(5400)
print("in 90 Minuten ist Pause")
time.sleep(2)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(199)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(251)
print("7,5 Minütige Pause ist um")
time.sleep(5400)
print("Pause für dich!")
time.sleep(2)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(199)
webbrowser.open("https://www.youtube.com/watch?v=FvGgFzagfI4")
time.sleep(251)
print("7,5 Minütige Pause ist um")
time.sleep(5400)
print("Schluss.")





